# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite rules to address specific style issues
Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: space
  Enabled: true

Style/PercentLiteralDelimiters:
  Enabled: true
  PreferredDelimiters:
    '%w': '[]'
    '%W': '[]'
    '%i': '[]'
    '%I': '[]'
    '%r': '{}'

Layout/SpaceAfterComma:
  Enabled: true
