plugins:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.5
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'

# Layout
Layout/LineLength:
  Max: 100

# Metrics
Metrics/ClassLength:
  Max: 100
  CountComments: false

Metrics/ModuleLength:
  Max: 100
  CountComments: false

Metrics/MethodLength:
  Max: 10
  CountComments: false
  AllowedMethods:
    - 'initialize'

Metrics/AbcSize:
  Max: 15

Metrics/CyclomaticComplexity:
  Max: 6

Metrics/PerceivedComplexity:
  Max: 7

Metrics/ParameterLists:
  Max: 3
  CountKeywordArgs: false

Metrics/BlockLength:
  Max: 25

# Style
Style/Documentation:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Style/StringLiterals:
  EnforcedStyle: single_quotes
  ConsistentQuotesInMultiline: true

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/GuardClause:
  Enabled: true
  MinBodyLength: 1

Style/ModuleFunction:
  Enabled: true
  EnforcedStyle: module_function

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

# Security
Security/Eval:
  Enabled: true

Security/Open:
  Enabled: true

# Performance
Performance/Count:
  Enabled: true

Performance/Detect:
  Enabled: true

# Additional cops
Lint/UselessAssignment:
  Enabled: true

Lint/DuplicateMethods:
  Enabled: true

Rails:
  Enabled: false
