# frozen_string_literal: true

source 'https://rubygems.org'

ruby '>= 3.0.0'

# Core web framework
gem 'roda', '~> 3.70'

# Database
gem 'sequel', '~> 5.70'
gem 'sqlite3', '~> 1.6'

# Server
gem 'puma', '~> 6.3'
gem 'rack', '~> 3.0'
gem 'rackup', '~> 2.2'

# Security
gem 'bcrypt', '~> 3.1'
gem 'jwt', '~> 2.7'
gem 'rack-cors', '~> 2.0'

# Utilities
gem 'base64', '~> 0.2.0'
gem 'benchmark', '~> 0.3'
gem 'dotenv', '~> 2.8'
gem 'json', '~> 2.6'
gem 'logger', '~> 1.6'
gem 'securerandom', '~> 0.3'

# Email
gem 'mail', '~> 2.8'

# Development
group :development do
  gem 'rerun', '~> 0.14'
end

# Authentication (removed unused gems)
# gem 'rodauth', '~> 2.32'
# gem 'rodauth-model', '~> 0.2'

# Testing
group :test do
  gem 'database_cleaner-sequel', '~> 2.0'
  gem 'factory_bot', '~> 6.2'
  gem 'faker', '~> 3.2'
  gem 'parallel_tests', '~> 4.2'
  gem 'rack-test', '~> 2.1'
  gem 'rspec', '~> 3.12'
  gem 'rspec-benchmark', '~> 0.6'
  gem 'rspec-json_expectations', '~> 2.2'
  gem 'simplecov', '~> 0.22'
  gem 'timecop', '~> 0.9'
  gem 'webmock', '~> 3.18'
end
